%YAML:1.0
model_path: "../3d_models/"
name_of_pcd: "LM6"
method_of_IG : 6
sampling_method_of_viewspace : 0
first_view_id : 0
octomap_resolution: 0.03
ground_truth_resolution: 0.002
num_of_max_iteration: 15
show: 0
move_wait : 0
nbv_net_path: "../nbv-net-sphere"
p_unknown_upper_bound: 0.65
p_unknown_lower_bound: 0.45
inner_sphere_radius_rate : 2.0
outer_sphere_radius_rate : 4.0
num_of_views : 1592
cost_weight: 0.5
his_on: 1
move_cost_on: 0
move_weight: 0.5
robot_cost_negtive: 1
skip_coefficient : 1.0
num_of_max_flow_node : -1
interesting_threshold : 0.65
see_threshold : 0.5
need_threshold : 0.3
skip_threshold : 0.2
visble_rate : 0.7
move_rate : 1.0
color_width: 640
color_height: 480
color_fx: 6.1040447998046875e+02
color_fy: 6.0888446044921875e+02
color_ppx: 3.2476354980468750e+02
color_ppy: 2.4834353637695313e+02
color_model: 2
color_k1: 1.2042199820280075e-01
color_k2: -2.1373499929904938e-01
color_k3: 5.3860000334680080e-03
color_p1: -2.1210000850260258e-03
color_p2: 0.
depth_scale: 1.0000000474974513e-03
